// Code generated by knobs gen; DO NOT EDIT.
// SAMPLE output — regenerate for your schema:
//   knobs gen --lang ts --endpoint <url> --api-key <key> --out knobs.gen.ts

export interface AppConfig {
  /** How many times to retry a failed request */
  maxRetries: number;
  featureX: boolean;
  tier: "gold" | "silver";
}

export const schemaHash = "sample0000000000000000000000000000000000000000000000000000000000";

export function typed(client: { getAll(): Record<string, unknown> }): AppConfig {
  return client.getAll() as unknown as AppConfig;
}
