package codegen

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/Rohan-Muslekar/knobs/internal/schema"
)

// identifierPattern matches a valid TypeScript identifier, per the field-key
// mapping: a bare `name: type;` member is only safe to emit when the field
// name is one of these; anything else must be a quoted property key.
var identifierPattern = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// propertyKey renders a field name as a valid TypeScript interface member
// key. A field name is untrusted input from whatever created the schema —
// it can contain spaces, punctuation, or start with a digit (e.g.
// "max retries", "2fa") — so it's emitted bare only when it's already a
// valid identifier; otherwise it's quoted (via strconv.Quote, which escapes
// the same way for a TS string literal as it does for a Go one) so the
// member is syntactically valid either way.
func propertyKey(name string) string {
	if identifierPattern.MatchString(name) {
		return name
	}
	return strconv.Quote(name)
}

// sanitizeDescription makes a field's description safe to embed inside a
// single-line `/** ... */` JSDoc comment. A description is untrusted input
// (it can be edited freely by anyone with schema access) and the emitted
// file is compiled downstream, so two things have to hold regardless of
// what the description contains:
//
//   - it can't span multiple lines, since a raw newline would break out of
//     the single-line comment onto a new, uncommented source line — so
//     newlines are collapsed to spaces;
//   - it can't close the comment early, since `*/` inside the text would
//     terminate the JSDoc there and let anything after it run as top-level
//     TypeScript — so every `*/` is neutralized into `* /`, which reads
//     fine as prose but can't parse as a comment terminator.
func sanitizeDescription(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "*/", "* /")
	return s
}

// EmitTypeScript renders def (and the schemaHash it was computed from) as a
// deterministic .gen.ts source string:
//
//   - an `AppConfig` interface with one member per field, typed per the
//     field-type -> TypeScript mapping (see tsType), optional (`?:`) for
//     non-required fields, with the field's description (if any) emitted as
//     a `/** ... */` doc comment directly above it;
//   - `export const schemaHash = "<schemaHash>"`;
//   - a typed accessor, `typed()`, that narrows an SDK client's untyped
//     `getAll()` to AppConfig.
//
// Field order in the interface is exactly def.Fields' order — the caller
// (the schema store) already gives fields a stable order, and EmitTypeScript
// doesn't re-sort them, so the same Definition always produces byte-for-byte
// identical output.
func EmitTypeScript(def schema.Definition, schemaHash string) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by knobs gen; DO NOT EDIT.\n")
	b.WriteString("// Field order matches the schema definition's field order.\n\n")
	b.WriteString("export interface AppConfig {\n")

	for _, f := range def.Fields {
		fieldType, err := tsType(f)
		if err != nil {
			return "", err
		}

		if f.Description != "" {
			fmt.Fprintf(&b, "  /** %s */\n", sanitizeDescription(f.Description))
		}

		optional := ""
		if !f.Required {
			optional = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", propertyKey(f.Name), optional, fieldType)
	}

	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "export const schemaHash = %q;\n\n", schemaHash)
	b.WriteString("export function typed(client: { getAll(): Record<string, unknown> }): AppConfig {\n")
	b.WriteString("  return client.getAll() as AppConfig;\n")
	b.WriteString("}\n")

	return b.String(), nil
}
