// Code generated by knobs gen; DO NOT EDIT.
// Field order matches the schema definition's field order.

package knobsconfig

import "encoding/json"

type Config struct {
	// Human-readable app name
	Name       string  `json:"name"`
	Nickname   string  `json:"nickname"`
	MaxRetries int64   `json:"maxRetries"`
	Threshold  float64 `json:"threshold"`
	Enabled    bool    `json:"enabled"`
	Metadata   any     `json:"metadata"`
	Timeout    string  `json:"timeout"`
	// Allowed values: "gold", "silver"
	Tier string `json:"tier"`
}

const SchemaHash = "testhash123"

func Typed(client interface{ GetAll() map[string]any }) (Config, error) {
	var cfg Config
	data, err := json.Marshal(client.GetAll())
	if err != nil {
		return cfg, err
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}
