// Code generated by knobs gen; DO NOT EDIT.
// Field order matches the schema definition's field order.

export interface AppConfig {
  /** Human-readable app name */
  name: string;
  nickname?: string;
  maxRetries: number;
  threshold: number;
  enabled: boolean;
  metadata: unknown;
  timeout: string;
  tier: "gold" | "silver";
}

export const schemaHash = "testhash123";

export function typed(client: { getAll(): Record<string, unknown> }): AppConfig {
  return client.getAll() as unknown as AppConfig;
}
