// Code generated by knobs gen; DO NOT EDIT.
// Field order matches the schema definition's field order.
//
// This is a SAMPLE of what `knobs gen --lang ts` emits for a project whose
// schema has maxRetries (int), featureX (bool), and tier (enum). In a real
// project you regenerate this file whenever the schema changes:
//   knobs gen --lang ts --endpoint <url> --api-key <key> --out src/knobs.gen.ts

export interface AppConfig {
  /** How many times to retry a failed request */
  maxRetries: number;
  featureX: boolean;
  tier: "gold" | "silver";
}

export const schemaHash = "sample0000000000000000000000000000000000000000000000000000000000";

export function typed(client: { getAll(): Record<string, unknown> }): AppConfig {
  return client.getAll() as unknown as AppConfig;
}
